;;; js-react-redux-yasnippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from js-react-redux-yasnippets.el

(autoload 'js-react-redux-yasnippets-initialize "js-react-redux-yasnippets"
"Initialize js-react-redux-yasnippets with yasnippet.")
(eval-after-load 'yasnippet '(js-react-redux-yasnippets-initialize))
(register-definition-prefixes "js-react-redux-yasnippets" '("js-react-redux-yasnippets-"))

;;; End of scraped data

(provide 'js-react-redux-yasnippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; js-react-redux-yasnippets-autoloads.el ends here
